import Email from "@/components/Email";
import Footer from "@/components/Footer";
import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import { Inter } from "next/font/google";
import Header from "../components/Header";
import Socials from "../components/Socials";
import "./globals.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter', 
}) 

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) { 
  return (
    <html lang="en" className={`${inter.variable}`}>
      <head>
        <link rel="shortcut icon" type="image/x-icon" href="/favicon.png" /> 
      </head>
      <body className="h-full text-black bg-background dark:bg-dark-background dark:text-dark-text font-playfair"> 
      <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        > 
            <Header/>
            {children}  
            <Footer /> 
            <Socials/> 
            <Email/>    
        </ThemeProvider>
      </body>
    </html>
  )
}
